Repository SDSamarasinghe/GoMart, pull requests merged in 2022-09, with the labels that each got.

#9 create interfaces to add product and edit products
  Code/gomart-backend/controllers/ProdController.js
  Code/gomart-backend/models/AddProductModel.js
  Code/gomart-backend/server.js
  Code/gomart-frontend/package-lock.json
  Code/gomart-frontend/package.json
  Code/gomart-frontend/public/index.html
  Code/gomart-frontend/src/App.js
  Code/gomart-frontend/src/components/Products/AdminRegistration.js
  Code/gomart-frontend/src/components/Products/AdvertiserForm.js
  Code/gomart-frontend/src/components/Products/EditAd.js
  Code/gomart-frontend/src/components/Products/ProductsCatelog.js
  Code/gomart-frontend/src/components/Products/img/add-product.png
  Code/gomart-frontend/src/components/Products/img/add.png
  Code/gomart-frontend/src/components/Products/img/handfree.jpg
Labels: enhancement

#10 fix some bugs in the server.js file
  Code/gomart-backend/package-lock.json
  Code/gomart-backend/server.js
  Code/gomart-frontend/src/components/Products/AdvertiserForm.js
Labels: bug

#7 Feedback management1
  Code/gomart-backend/controllers/ComplaintsController.js
  Code/gomart-backend/controllers/FeedbackController.js
  Code/gomart-backend/models/ComplaintsModel.js
  Code/gomart-backend/models/FeedbackModel.js
  Code/gomart-backend/routes/ComplaintsRoutes.js
  Code/gomart-backend/routes/feedbackRoutes.js
  Code/gomart-backend/server.js
Labels: bug

#11 create admin dashboard.
  Code/gomart-frontend/package-lock.json
  Code/gomart-frontend/package.json
  Code/gomart-frontend/public/index.html
  Code/gomart-frontend/src/App.js
  Code/gomart-frontend/src/components/Products/AdminViewAds.js
  Code/gomart-frontend/src/components/Products/Admins.css
  Code/gomart-frontend/src/components/Products/AdvertiserForm.js
  Code/gomart-frontend/src/components/Products/ProductsCatelog.js
  package-lock.json
  package.json
Labels: bug, documentation, duplicate

#12 get all the data from database and retrive into admin dashboard
  Code/gomart-frontend/src/App.js
  Code/gomart-frontend/src/components/Products/AdminViewAds.js
  Code/gomart-frontend/src/components/Products/ProductsCatelog.js
Labels: duplicate, enhancement

#13 add vertical menu for admin dashboard
  Code/gomart-frontend/package-lock.json
  Code/gomart-frontend/package.json
  Code/gomart-frontend/public/index.html
  Code/gomart-frontend/src/components/Navigator/Navigator.js
  Code/gomart-frontend/src/components/Navigator/img/carts.png
  Code/gomart-frontend/src/components/Products/AdminViewAds.js
Labels: bug, documentation, duplicate

#15 add admin login and register to the system
  Code/gomart-backend/models/UserModel.js
  Code/gomart-backend/routes/userManageRoutes.js
  Code/gomart-frontend/src/App.js
  Code/gomart-frontend/src/components/Products/AdminViewAds.js
  Code/gomart-frontend/src/components/Products/AdvertiserForm.js
  Code/gomart-frontend/src/components/Products/ProductsCatelog.js
  Code/gomart-frontend/src/components/Products/navigator.css
  Code/gomart-frontend/src/components/Users/Login.js
  Code/gomart-frontend/src/components/Users/Profile.js
  Code/gomart-frontend/src/components/Users/Register.js
  Code/gomart-frontend/src/components/Users/user.css
Labels: documentation, duplicate, enhancement, help wanted, question

#16 ++updated
  Code/gomart-backend/models/UserModel.js
  Code/gomart-backend/routes/userManageRoutes.js
  Code/gomart-frontend/package-lock.json
  Code/gomart-frontend/package.json
  Code/gomart-frontend/public/index.html
  Code/gomart-frontend/src/App.js
  Code/gomart-frontend/src/components/Navigator/Navigator.js
  Code/gomart-frontend/src/components/Navigator/img/carts.png
  Code/gomart-frontend/src/components/Products/AdminViewAds.js
  Code/gomart-frontend/src/components/Products/Admins.css
  Code/gomart-frontend/src/components/Products/AdvertiserForm.js
  Code/gomart-frontend/src/components/Products/ProductsCatelog.js
  Code/gomart-frontend/src/components/Products/navigator.css
  Code/gomart-frontend/src/components/Users/Login.js
  Code/gomart-frontend/src/components/Users/Profile.js
  Code/gomart-frontend/src/components/Users/Register.js
  Code/gomart-frontend/src/components/Users/user.css
  package-lock.json
  package.json
Labels: bug, documentation, enhancement

#17 Product management
  Code/gomart-backend/server.js
Labels: bug, documentation, duplicate

#19 make some changes for server.js file
  Code/gomart-backend/server.js
  Code/gomart-frontend/src/components/Feedbacks/addFeedback.js
Labels: documentation, duplicate

#20 change package lock json
  Code/gomart-backend/package-lock.json
Labels: documentation, duplicate

#4 Delivery management
  Code/gomart-backend/models/order.js
  Code/gomart-backend/package-lock.json
  Code/gomart-backend/package.json
  Code/gomart-backend/routes/order.js
Labels: documentation

#21 commit order
  Code/gomart-backend/server.js
Labels: bug, duplicate

#26 Product management
  Code/gomart-backend/package-lock.json
  Code/gomart-backend/package.json
  Code/gomart-backend/server.js
  Code/gomart-frontend/src/components/Feedbacks/addFeedback.js
  package-lock.json
  package.json
Labels: documentation, duplicate
